---
- name: Build Kafka AMI
  hosts: all
  become: yes
  gather_facts: yes
#  vars_files:
#    - roles/kafka/defaults/main.yaml
  roles:
    - { role: system, tags: system }
    - { role: zookeeper, tags: zookeeper }
    - { role: kafka, tags: kafka }
    - { role: manager, tags: manager }
    - { role: monitoring, tags: monitoring }
    - { role: verify, tags: verify }
    - { role: finalize, tags: finalize }
